In [2]:
# As seen here: 
# https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0#.cfza6gc0d

In [3]:
import gym
import numpy as np

In [4]:
env = gym.make('FrozenLake-v0')

[2017-01-03 22:09:25,617] Making new env: FrozenLake-v0


In [5]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [6]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.4715


In [7]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  4.87812239e-01   3.23482266e-03   8.52054586e-03   8.32036135e-03]
 [  0.00000000e+00   7.26449332e-05   4.66800626e-04   4.22433770e-01]
 [  3.91059855e-01   5.32453771e-03   8.37028192e-04   9.36179396e-04]
 [  4.69669299e-04   4.57863934e-03   3.95226715e-04   6.98397187e-03]
 [  4.99751988e-01   5.98789267e-04   2.11509002e-04   1.50517358e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.60427613e-02   5.35496210e-05   4.48471732e-04   1.68811502e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.14277300e-05   6.83818453e-04   1.21929642e-03   4.50249412e-01]
 [  2.63636152e-03   6.05828535e-01   4.60783711e-04   2.02405959e-03]
 [  2.79413933e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   6.28141676e-01   0